### ISSUE TITLE
gherkin-testcafe command not found

### ISSUE THREAD

**Issue by daniellboy** [kiwigrid/gherkin-testcafe#13]
I already run this command `npm - gherkin-testcafe cucumber`. but when i try execute `gherkin-testcafe`, give me error message `bash: gherkin-testcafe: command not found`. how can i solved this issue?

**Comment by Lukas-Kullmann** [comment]
Hi @daniellboy.

when you want to run gherkin-testcafe via CLI, please make sure, the package is installed. When it is installed, run it with `npx gherkin-testcafe -d tests/**/*.js -s tests/**/*.feature -b firefox` if you use npm or `yarn run gherkin-testcafe -d tests/**/*.js -s tests/**/*.feature -b firefox` with yarn. 
Please make sure you run it in the same directory that you installed the package in.

Alternatively, you can install the package globally (`npm i -g gherkin-testcafe`). This will make the `gherkin-testcafe` be available from everywhere.

**Comment by daniellboy** [comment]
I got this error `Cannot find module 'testcafe/lib/errors/runtime'`

**Comment by skullz03** [comment]
npx gherkin-testcafe --steps tests/**/*.js --specs tests/**/*.feature --browsers firefox
npx: installed 1 in 9.74s
Path must be a string. Received undefined
npx: installed 68 in 23.974s
C:\Users\A418097\AppData\Roaming\npm-cache\_npx\23380\node_modules\gherkin-testcafe\main.js
Cannot find module 'testcafe/lib/errors/runtime'


How do you run these test cases ? :(

**Comment by skullz03** [comment]
your readme doc says run this command - gherkin-testcafe>gherkin-testcafe --steps examples/**/*.js --specs examples/**/*.feature --browsers firefox      I get an error 
```
'gherkin-testcafe' is not recognized as an internal or external command,
operable program or batch file.
```
