### ISSUE TITLE
Support for TestCafé Live

### ISSUE THREAD

**Issue by JakeTheSnake** [kiwigrid/gherkin-testcafe#15]
Hello, is it possible to run [TestCafé Live](https://github.com/DevExpress/testcafe-live) with gherkin-testcafé?

**Comment by Lukas-Kullmann** [comment]
Hi @JakeTheSnake!

Unfortunately, it is not possible to use TestCafé Live with gherkin-testcafe at the moment.
And as of now, I do not plan to add support myself.

It seems to be a nice feature however. Please feel free to submit a PR to add support! :)

**Comment by Lukas-Kullmann** [comment]
Beginning from version 2, testcafe live is supported via CLI and programming interface.
