### ISSUE TITLE
setLocalStorageItem(key, value) Example

### ISSUE THREAD

**Issue by cpeople2** [kiwigrid/gherkin-testcafe#16]
Hello, can you please provide an example of how and where to setLocalStorageItem(key, value) within the code? I am unable to setLocalStorage with my token and have tried many different ways to no avail. Your response is very much appreciated. Thanks!

**Comment by Lukas-Kullmann** [comment]
Hi @cpeople2,

please note, that handling local storage from within the test is a general TestCafé problem and not specific to zhe gherkin-testcafe package.

Please refer to [this issue] (https://github.com/DevExpress/testcafe/issues/1325) to see how to set local storage items using ClientFunctions with TestCafé.
