### ISSUE TITLE
Updating to latest testcafe version

### ISSUE THREAD

**Issue by msusur** [kiwigrid/gherkin-testcafe#25]
I am assuming this has already been thought but is there a reason why not use the [latest testcafe (v1.0.0)](https://github.com/DevExpress/testcafe/releases/tag/v1.0.0) version? 

I saw in 121e056017e9485464a608392fd1e8ce66fcd346 @Lukas-Kullmann bumped the version to v.0.23 but was wondering what are the complication to upgrade it to v.1.0?

**Comment by Lukas-Kullmann** [comment]
There is no particular reason behind this.
I just have not tested if the versions are compatible. I hope I find time this week to address this issue and update the version.

**Comment by Lukas-Kullmann** [comment]
So, I investigated the problem today and it turns out, that the internals of testcafe have changed a lot.
Since the changes do not allow the current workflow, I will publish this as version 2 with breaking changes in the next days.

**Comment by Lukas-Kullmann** [comment]
gherkin-testcafe@2.2.0 is now released and uses testcafe@1.0.0 .
