### ISSUE TITLE
Running tests with multiple tags runs only 1st test.

### ISSUE THREAD

**Issue by bbonczek** [kiwigrid/gherkin-testcafe#32]
We are currently upgrading testcafe and gherkin-testcafe to new version, and it seems like running tests with multiple tags is not working. We use only CLI interface. To run e2e tests we use this method:

`gherkin-testcafe chrome e2e/*.feature e2e/step-definitions/*.js --tags @eHim @mobile @eHimLarge ~@ignore -a \"http-server -p 4200 ./dist/web-drive-profiles\" --appInitDelay 5000 -c 6`

This command should run all tests decorated with @eHIM @mobile & @eHIMLarge tags. What happens now, is only tests decorated with '@eHIM' (1st tag) are ran.

**Comment by Lukas-Kullmann** [comment]
Hey @bbonczek,

sorry for the late response.
You have to separate tags by comma for this to work:

    gherkin-testcafe chrome e2e/*.feature e2e/step-definitions/*.js --tags @eHim,@mobile,@eHimLarge,~@ignore -a \"http-server -p 4200 ./dist/web-drive-profiles\" --appInitDelay 5000 -c 6

I upgraded the readme with your use-case.
