### ISSUE TITLE
Is there a way to skip a test?

### ISSUE THREAD

**Issue by dthisner** [kiwigrid/gherkin-testcafe#48]
I can't seem to figure out how I can disable/skip test, with TestCafe you do: `test.skip`, how would that work with gherkin-testcafe?

**Comment by eddiegroves** [comment]
Add a tag to the scenario or feature to skip such as `@skip` and pass it through with `--tags ~@skip`.

```
@skip # <--- Skip all scenarios in the feature
Feature: The big search feature

  I want to find TestCafe repository by Google search

  @googleHook @skip <!-- or just skip this one
  Scenario: Searching for TestCafe by Google
    Given I open Google's search page
    When I am typing my search request "github TestCafe" on Google
    And I am pressing "enter" key on Google
    Then I should see that the first Google's result is "DevExpress/testcafe:"
```

**Comment by Lukas-Kullmann** [comment]
In addition to what @eddiegroves said, you can also use the command line options `-t`, `-T`, `-f` and `-F` to filter down tests by name.

**Comment by dthisner** [comment]
Thanks, was trying to avoid using tags, since sometimes I have developer using the tests and making sure they are using it correctly and disabling tests correctly (when needed). I will see if I can get some setup that makes it easy :) 

Thanks a lot for the quick answers :)
