### ISSUE TITLE
Scenario are not being registered 

### ISSUE THREAD

**Issue by dthisner** [kiwigrid/gherkin-testcafe#49]
This is really weird, I don't know how this is triggered, maybe for the amount of scenarios I have. Take a peek at my `register.feature` file, The last scenario has a tag named `@only`, but, when I tell TestCafe-Gherkin to run that specific tag, it tells me there is no tests for it to run.

If I move that scenario higher up in the list, then it is able to locate it and run it without any issues. 

This is happening to 2 of my feature files now. I'm I doing something wrong? 

```
Feature: User is able to register

  @register @failingRegister
  Scenario: Should NOT be able to register without filling in any information
    Given I am at the register page
    When I am register with email "" and password "" with confirm password ""
    Then I should NOT be able to press the signup button

  @register @failingRegister
  Scenario: Should NOT be able to register without filling in password
    Given I am at the register page
    When I am register with email "bob@bobsTown.com" and password "" with confirm password ""
    Then I should NOT be able to press the signup button

  @register @failingRegister
  Scenario: Should NOT be able to register without filling in confirm password
    Given I am at the register page
    When I am register with email "bob@bobsTown.com" and password "AmazingPass!2387" with confirm password ""
    Then I should NOT be able to press the signup button

  @register @failingRegister
  Scenario: Should NOT be able to register if password is fewer then 8 characters
    Given I am at the register page
    When I am register with email "bob@bobsTown.com" and password "aD$3!2j" with confirm password "aD$3!2j"
    Then I should NOT be able to press the signup button

  @register @successfullRegistration @only
  Scenario: Should be able to register an account and continue without verifying email
    Given I am at the register page
    When I am register with email "bob@bobsTown.com" and password "AmazingPass!2387" with confirm password "AmazingPass!2387"
    Then I should be able to press the signup button
    Then I should be able to see successfull signup screen
    Then I should be able to continue to account setup

  @register @failingRegister
  Scenario: Should NOT be able to register with miss matching passwords
    Given I am at the register page
    When I am register with email "bob@bobsTown.com" and password "ThisWas4321OneThing" with confirm password "ThisWasAnotherThing"
    Then I should see must be the same as password
    Then I should NOT be able to press the signup button

  @register @successfullRegistration @only
  Scenario: Should be able to register an account and continue without verifying email
    Given I am at the register page
    When I am register with email "bob@bobsTown.com" and password "AmazingPass!2387" with confirm password "AmazingPass!2387"
    Then I should be able to press the signup button
    Then I should be able to see successfull signup screen
    Then I should be able to verify my email
    Then I should be able to continue setting up my account
```

If I run all test without using tags, then it is ignoring the test as well. 

TestCafe version:  1.4.1
gherkin-testcafe version: 2.4.0

No tests to run. Either the test files contain no tests or the filter function is too restrictive

**Comment by dthisner** [comment]
Deleted my node_modules and re-installed it, seemed to have fixed it

**Comment by Lukas-Kullmann** [comment]
Sorry to hear that the error still persists.

Could you verify for me if the error still occurs if you only load that specific feature file (no other files)?

**Comment by Lukas-Kullmann** [comment]
Well, I can't reproduce this error. I tried 

- `gherkin-testcafe chrome example.feature`: It ran all six tests
- `gherkin-testcafe chrome example.feature --tags @dennis`: It ran the fifth test
- `gherkin-testcafe chrome example.feature --tags @dennis,~@roleSuperI`: It did not find tests
- `gherkin-testcafe chrome example.feature --tags ~@roleSuperI`: It ran all test except the fifth one

This all seems correct to me.

**Comment by Lukas-Kullmann** [comment]
I just published v2.4.1 which updates gherkin to a new version.
Could you try if this fixes your issue? It seems to me that your issue comes from a wrong parsing of the feature files, so maybe they changed something that magically helps. :D

> Is there a way to get more debugging out?

Unfortunately, no. You could run your tests in debug mode and set breakpoints in the gherkin-testcafe files, but I doubt that it would tell you much if you do not know exactly how gherkin-testcafe works.

I'm thinking about hooking into the [--dev flag](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--dev) to generate more debug info. At the moment I don't have the time to do this tough.

**Comment by dthisner** [comment]
Thanks Lukas!
It seems to have fixed it, I will test around today and if I can't make the issue to occur again, I close this issue :)

**Comment by dthisner** [comment]
Looking good, closing this issue :)
