### ISSUE TITLE
Refresh page (with # in url) in test steps

### ISSUE THREAD

**Issue by showenx** [kiwigrid/gherkin-testcafe#50]
hi,
I am trying to refresh an Augular page in test steps.
e.g. url = 'http://localhost:8080/main#/account'
 
Having tried following ways, but none of them seems working right for page refresh with *#*

- `await t.navigateTo(url);`
- `await t.eval(() => location.reload(true));`
-   `const reloadPage = ClientFunction(() => {`
     ` location.reload(true);`
  `});`
 `await t.reloadPage();`
- `const reloadPage = ClientFunction(() => {`
     ` location.reload(true);`
  `});`
` const boundReloadPage = reloadPage.with({`
    `boundTestRun: t,`
  `});`
`await boundReloadPage();`

**Comment by Lukas-Kullmann** [comment]
Hey @showenx,
this seems more like a testcafe issue than an issue with gherkin-testcafe.

Please try using the latest testcafe version and if the problem still persists, open an issue at the testcafe repo.
