### ISSUE TITLE
Improve tags filtering

### ISSUE THREAD

**Issue by Arthy000** [kiwigrid/gherkin-testcafe#52]
Hello,

At the moment, a test is included if any of the including tags is present.

Example:
```
@tag1 @tag2
Scenario1: ...

@tag1
Scenario2: ...

@tag2
Scenario3: ...
```

Using runner.tags('@tag1','@tag2'), all 3 scenarios would run.

I'd like to be able to use runner.tags('@tag1 AND @tag2') to only include Scenario1 in the test run.
I haven't found any way to do this with gherkin-testcafe, though the possibility exists in Cucumber (https://cucumber.io/docs/cucumber/api/#tag-expressions)

**Comment by mariogalea** [comment]
This would be a very ideal addition to the Tagging functionality.
