### ISSUE TITLE
It does not work with Browserstack

### ISSUE THREAD

**Issue by robert-dzikowski** [kiwigrid/gherkin-testcafe#61]
So I installed https://github.com/DevExpress/testcafe-browser-provider-browserstack 
ordinary Test Cafe tests run on browserstack. But when I try to run Gherkin tests, e.g.
`TestCafeStudio\node_modules\.bin\gherkin-testcafe browserstack:chrome TestCafeStudio/tests/*.ts TestCafeStudio/tests/*.feature`
I get error
`ERROR Unable to find the browser. "browserstack" is not a browser alias or path to an executable file.`

**Comment by Lukas-Kullmann** [comment]
Well, we use gherkin-testcafe together with browserstack and it works. I just tested the latest versions and it loaded the tests in browserstack.
Could you verify for me that you installed the packages into the same folder by running 

    npm ls gherkin-testcafe testcafe-browser-provider-browserstack testcafe

It should print something like

```
my-package@0.0.0 /path/to/folder
├── gherkin-testcafe@2.5.0 
├── testcafe@1.8.3 
└── testcafe-browser-provider-browserstack@1.13.0-alpha.1 
```

**Comment by robert-dzikowski** [comment]
You are write my configuration is wrong, I only see gherkin-testcafe and testcafe.
Can you write how to correctly install gherkin-testcafe and testcafe-browser-provider-browserstack, please? Let's say that my project is in test-project folder.

**Comment by Lukas-Kullmann** [comment]
Well, you just `npm install testcafe-browser-provider-browserstack` in your `test-project` folder.

**Comment by robert-dzikowski** [comment]
Thanks
