### ISSUE TITLE
Typed parameters in steps?

### ISSUE THREAD

**Issue by corneliutusnea** [kiwigrid/gherkin-testcafe#63]
Hi,

Is it possible to make the parameters for the steps typed?
`async (t, [param1, param2, param3, param4])`
Previously when the signature was `async (t, param1, param2, param3, param4)` I could type them like this: `async (t: TestController, param1: string, param2: number, param3: MyCustomType)`

**Comment by Lukas-Kullmann** [comment]
You could type it as `async (t, [param1, param2, param3, param4]: [string, number, MyCustomType, any])`.
