### ISSUE TITLE
how to pass additional parameters to testcafe like --app

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [kiwigrid/gherkin-testcafe#64]
hi how to pass additional parameters to testcafe?

sometimes i launch e2e tests with locally launched application with 
--app \"yarn start\" --app-init-delay 70000 --proxy-bypass http://localhost:4200/

how to achieve that in gherkin-testcafe?

**Comment by Lukas-Kullmann** [comment]
gherkin-testcafe forwards all arguments to testcafe. You can just gherkin-testcafe instead of testcafe and it should work as expected.

If you have any problems, please open another issue. 🙂

**Comment by AdaskoTheBeAsT** [comment]
ok it was my mistake - it really works :) thanks
