### ISSUE TITLE
New maintainers wanted

### ISSUE THREAD

**Issue by Lukas-Kullmann** [kiwigrid/gherkin-testcafe#71]
Due to people leaving our company, we are not able any more to maintain this project. This is why we search for a new maintainer.

If no new maintainer is found, we unfortunately have to retire this project by the beginning of November 2020.

If you are interested to maintain this project, please leave a comment here and I will be in touch.

**Comment by combmag** [comment]
HI @Lukas-Kullmann , i can help out if you want

**Comment by Lukas-Kullmann** [comment]
Hey @combmag 
thank you for the offer. However, I do not think, that you have enough experience to maintain a project like this. I have sent you an email further explaining my reasoning. I hope you have received it.

**Comment by Arthy000** [comment]
Hey, I'd be willing to maintain it as I've been using for the better part of two years and I kinda need it anyway :D
